# Generated by Django 2.2.3 on 2019-08-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_userprofile_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='form_submit',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
